[[mgr.prepend_keymap]]
on   = [ "j" ]
run  = "arrow -1"
desc = "Move cursor up"

[[mgr.prepend_keymap]]
on   = [ "k" ]
run  = "arrow 1"
desc = "Move cursor down"

[[mgr.prepend_keymap]]
on   = [ "K" ]
run  = "seek 1"

[[mgr.prepend_keymap]]
on   = [ "J" ]
run  = "seek -1"
